name: github-actions-publish
run-name: ${{ github.actor }} is publishing website
on: [push]
jobs:
  pusblish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
      - uses: actions/setup-node@v3    
        with:
          node-version: '14'
      - run: npm install
      - run: git config --global user.email "sumanbogati@gmail.com"
      - run: git config --global user.name "Suman Bogati" 

      - run: git remote set-url origin https://suman:${{ secrets.GH_SECRET }}@github.com/suman/react-typescript-todo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
	 - run: npm run deploy
      

