name: github-actions-publish
run-name: ${{ github.actor }} is publishing website
on: [push]
jobs:
  pusblish-website:
    runs-on: ubuntu-latest
    steps:
      - name: my first action
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
        with:
          node-version: '14'
      - run: npm install
      - run:  git config --global user.email 'sumanbogati@gmail.com'
      - run:  git config --global user.name 'suman'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git remote set-url origin https://suman:${{ secrets.GH_SECRET }}@github.com/suman/react-typescript-todo
      - run: npm run deploy
      

